name: Daily Commit

on:
  schedule:
    - cron: '50 12 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step with your email included in the name
      - name: "Commit changes with email: 23f1000747@ds.study.iitm.ac.in"
        run: |
          # Create a simple file to commit
          echo "Daily update - $(date)" > update.txt

          # Add, commit, and push the changes
          git add update.txt
          git commit -m "Daily commit - $(date)"
          git push
